name: Trigger auto deployment for smart-drip

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/smart-drip-AutoDeployTrigger-e9ef8c9e-cdb4-440c-ad93-091ffb8baafe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SMARTDRIP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SMARTDRIP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SMARTDRIP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SMARTDRIP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMARTDRIP_REGISTRY_PASSWORD }}
          containerAppName: smart-drip
          resourceGroup: smart_drip
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


